'use strict';
const assert=require('node:assert/strict'),W=require('./server/world.cjs'),P=require('./server/groq.cjs');
(async()=>{const state=W.initial('Rowan','wizard'),secret='test-signing-secret';const save=W.sign(state,secret);assert.deepEqual(W.verify(save,secret),state);assert.throws(()=>W.verify(save+'X',secret));assert.throws(()=>W.verify(save,'different'));
const plan={kind:'check',ability:'INT',dc:12,proficient:true,advantage:'normal',resource:'spell',stakes:'Understand the rune.',intent:'Read it.'};const a=W.resolve(state,plan,()=>10);assert.equal(a.resolution.roll.total,15);assert(a.resolution.roll.success);assert.equal(a.state.slots,2);assert.equal(state.slots,3);
const empty={...state,slots:0};assert(W.resolve(empty,plan).resolution.blocked);const potion=W.resolve({...state,hp:1},{...plan,kind:'none',resource:'potion'},()=>4);assert.equal(potion.state.hp,11);assert.equal(potion.state.potions,1);
assert.equal(W.resolve(state,{...plan,kind:'attack',dc:25},()=>20).resolution.roll.success,true);assert.equal(W.resolve(state,{...plan,kind:'attack',dc:5},()=>1).resolution.roll.success,false);
const result={narrative:'A road opens towards Greyhaven.',location:'Greyhaven road',time:'Morning',suggestions:['Walk on'],memory:'Rowan left Blackthorn for Greyhaven.',inventory:state.inventory,npcs:['Dara: river merchant'],quests:['Find passage downriver'],places:['Greyhaven: river port'],hpChange:500,goldChange:500,xpGain:500,rest:'none'};const updated=W.apply(a.state,result,'Leave the village',a.resolution);assert.equal(updated.location,'Greyhaven road');assert.equal(updated.gold,60);assert.equal(updated.xp,25);assert.equal(updated.hp,state.maxHp);assert.equal(updated.turn,1);assert.equal(updated.history.length,1);
const blocked=W.resolve(empty,plan);assert.equal(W.apply(blocked.state,result,'Cast spell',blocked.resolution).gold,10);assert.throws(()=>W.apply(state,{...result,narrative:null},'x',a.resolution));
let requests=0;const env={GROQ_QUOTA_MODE:'shared',GROQ_API_KEYS:JSON.stringify(['gsk_test_one','gsk_test_two'])};const limited=async()=>{requests++;return {status:429,headers:new Headers({'retry-after':'3'})}};P.resetForTests();await assert.rejects(P.generate([],{}, {env,fetcher:limited}),e=>e.status===429);assert.equal(requests,1);await assert.rejects(P.generate([],{}, {env,fetcher:limited}),e=>e.status===429);assert.equal(requests,1);
P.resetForTests();requests=0;const auth=async()=>{requests++;return requests===1?{status:401}:{status:200,ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:'{"ok":true}'}}]})}};assert.deepEqual(await P.generate([],{}, {env,fetcher:auth}),{ok:true});assert.equal(requests,2);
P.resetForTests();requests=0;const unavailable=async()=>{requests++;return {status:503}};await assert.rejects(P.generate([],{}, {env,fetcher:unavailable}));assert.equal(requests,2);
// Independently owned organisations have independent cooldowns.
P.resetForTests();const separate={...env,GROQ_QUOTA_MODE:'separate'};const used=[];
const split=async(url,options)=>{const key=options.headers.Authorization;used.push(key);if(key.endsWith('one'))return {status:429,headers:new Headers({'retry-after':'120'})};return {status:200,ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:'{"ok":true}'}}]})}};
assert.deepEqual(await P.generate([],{}, {env:separate,fetcher:split}),{ok:true});assert.equal(used.length,2);
await P.generate([],{}, {env:separate,fetcher:split});assert.equal(used.length,3);assert(used[2].endsWith('two'));
P.resetForTests();let cooldownCalls=0;const allLimited=async()=>{cooldownCalls++;return {status:429,headers:new Headers({'retry-after':cooldownCalls===1?'120':'15'})}};
await assert.rejects(P.generate([],{}, {env:separate,fetcher:allLimited}),e=>e.status===429&&e.retryAfter<=15);assert.equal(cooldownCalls,2);
await assert.rejects(P.generate([],{}, {env:separate,fetcher:allLimited}),e=>e.status===429);assert.equal(cooldownCalls,2);
const fs=require('node:fs');for(const file of fs.readdirSync('dist')){assert(!/gsk_[a-zA-Z0-9]{20}/.test(fs.readFileSync('dist/'+file,'utf8')),'No keys in browser assets')}
console.log('Open-world checks passed: signed saves, server dice, resource limits, state bounds, rate-limit cooldown, auth failover, provider failover, no browser keys.');})().catch(e=>{console.error(e);process.exit(1)});
