'use strict';
const assert=require('node:assert/strict');
const world=require('../server/world.cjs');
const tactical=require('../server/tactical.cjs');
const secret='0123456789abcdef0123456789abcdef';
const high=(min,max)=>max-1;
function test(name,fn){try{fn();console.log('✓',name)}catch(error){console.error('✗',name);throw error}}
test('derives exploration graph from current location and exits',()=>{const state=world.initial('Map Tester','fighter'),exploration=tactical.deriveExploration(state);assert.equal(exploration.nodes.length,5);assert.equal(exploration.edges.length,4);assert.ok(exploration.nodes.find(node=>node.id===exploration.currentId)?.name.includes('road to Blackthorn'))});
test('spatial enrichment survives signed save round trip',()=>{const state=tactical.enrichSpatial(world.initial('Signer','rogue')),token=world.sign(state,secret),verified=world.verify(token,secret);assert.ok(verified.spatial.exploration.nodes.length>=4);assert.equal(verified.combat.active,false);assert.deepEqual(verified.combat.reachable,[])});
test('starts a deterministic tactical encounter with server reachability',()=>{const state=tactical.startEncounter(world.initial('Seren','fighter'),'Grave hound');assert.equal(state.combat.active,true);assert.equal(state.combat.actors['enemy-1'].name,'Grave hound');assert.equal(state.combat.grid.width,12);assert(state.combat.reachable.length>0)});
test('movement enforces speed and bounds',()=>{let state=tactical.startEncounter(world.initial('Mover','fighter'),'Foe');let result=tactical.move(state,11,7,high);assert.equal(result.ok,false);result=tactical.move(state,3,4,high);assert.equal(result.ok,true);assert.equal(result.state.combat.actors.hero.movementSpentFt,5)});
test('dash consumes the action and doubles movement allowance',()=>{const state=tactical.startEncounter(world.initial('Dasher','fighter'),'Foe'),result=tactical.dash(state);assert.equal(result.ok,true);assert.equal(result.state.combat.actors.hero.actionUsed,true);assert.equal(result.state.combat.actors.hero.dashed,true);assert.ok(tactical.reachable(result.state).length>20)});
test('disengage prevents opportunity attacks when leaving reach',()=>{const state=tactical.startEncounter(world.initial('Scout','rogue'),'Foe');state.combat.actors.hero.x=8;state.combat.actors.hero.y=4;const disengaged=tactical.disengage(state),hp=disengaged.state.hp,result=tactical.move(disengaged.state,7,4,high);assert.equal(result.ok,true);assert.equal(result.state.hp,hp);assert.equal(result.state.combat.actors['enemy-1'].reactionAvailable,true)});
test('leaving reach without disengage triggers an opportunity attack',()=>{const state=tactical.startEncounter(world.initial('Scout','rogue'),'Foe');state.combat.actors.hero.x=8;state.combat.actors.hero.y=4;const hp=state.hp,result=tactical.move(state,7,4,high);assert.equal(result.ok,true);assert.ok(result.state.hp<hp);assert.equal(result.state.combat.actors['enemy-1'].reactionAvailable,false)});
test('fighter melee range is server-enforced',()=>{const state=tactical.startEncounter(world.initial('Fighter','fighter'),'Foe');let result=tactical.attack(state,'enemy-1',high);assert.equal(result.ok,false);state.combat.actors.hero.x=8;state.combat.actors.hero.y=4;result=tactical.attack(state,'enemy-1',high);assert.equal(result.ok,true);assert.ok(result.state.combat.actors['enemy-1'].hp<result.state.combat.actors['enemy-1'].maxHp)});
test('rogue shortbow is ranged and uses d6 plus DEX damage',()=>{const state=tactical.startEncounter(world.initial('Rogue','rogue'),'Foe');state.combat.grid.cells={};const before=state.combat.actors['enemy-1'].hp;let rolls=[15,4];const result=tactical.attack(state,'enemy-1',()=>rolls.shift()??4);assert.equal(result.ok,true);assert.equal(result.state.combat.actors['enemy-1'].hp,before-7,'4 on d6 + 3 should deal exactly 7 damage from range')});
test('total cover blocks a ranged attack',()=>{const state=tactical.startEncounter(world.initial('Mage','wizard'),'Foe');state.combat.grid.cells['5,4']={x:5,y:4,terrain:'blocked',cover:'total'};const result=tactical.attack(state,'enemy-1',high);assert.equal(result.ok,false);assert.match(result.summary,/cover/i)});
test('enemy turn advances round and attacks or closes distance',()=>{const state=tactical.startEncounter(world.initial('Hero','fighter'),'Foe');state.combat.actors.hero.x=8;state.combat.actors.hero.y=4;const hp=state.hp,result=tactical.endTurn(state,high);assert.equal(result.ok,true);assert.equal(result.state.combat.round,2);assert.equal(result.state.combat.turn,'hero');assert.ok(result.state.hp<hp)});
console.log('AIDungeonMaster port regression checks passed.');
