'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const dist=path.resolve(__dirname,'../dist');
const read=name=>fs.readFileSync(path.join(dist,name),'utf8');
const classes={fighter:{hp:24,ac:16,slots:0,weapon:'Longsword'},rogue:{hp:18,ac:14,slots:0,weapon:'Shortbow'},wizard:{hp:14,ac:12,slots:3,weapon:'Fire Bolt'}};
const prologue='Rain beads on your cloak. Ahead, Blackthorn huddles beneath a ruined abbey. Its bell tower has no bell.\n\nThe road is yours. What do you do?';
function stateFor(cls='fighter',name='Tester'){const c=classes[cls];return {version:3,id:'dom-campaign',turn:0,name,cls,level:2,xp:0,hp:c.hp,maxHp:c.hp,ac:c.ac,slots:c.slots,potions:2,gold:10,secondWindReady:cls==='fighter',location:'The road to Blackthorn',time:'Dusk, first day',inventory:[c.weapon,'Travelling cloak','Bedroll','Rations (3 days)',...(cls==='wizard'?['Spellbook']:[])],npcs:[],quests:['Discover why Blackthorn’s dead are walking—or choose your own road.'],places:['Blackthorn','The Hollow Marches'],memory:'Opening memory.',history:[],prologue,narrative:prologue,suggestions:['Ask the woman','Head west','Follow the bell'],lastRoll:null}}
const response=(status,body)=>({status,ok:status>=200&&status<300,json:async()=>body});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,message){for(let i=0;i<80;i++){if(fn())return;await wait(5)}throw new Error(message)}
function browserStubs(w){w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.confirm=()=>true;if(w.HTMLDialogElement){w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false}}try{Object.defineProperty(w.crypto,'randomUUID',{value:()=>`00000000-0000-4000-8000-${String(Date.now()).slice(-12)}`})}catch{}}
async function openWorld(saved){
  const dom=new JSDOM(read('index.html'),{url:'http://game.test/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;browserStubs(w);if(saved!==undefined)w.localStorage.setItem('astra-open-world-v3',saved);
  let state=null,seq=0;w.fetch=async(url,options={})=>{if(!options.method||options.method==='GET')return response(200,{configured:true,mode:'open-world',version:3,build:'dom-test'});const body=JSON.parse(options.body||'{}');if(body.start===true){state=stateFor(body.cls,(body.name||'').trim()||'Rowan');return response(200,{state,save:'dom-save-'+(++seq)+'-abcdefghijk'})}if(/rate limit/i.test(body.action||''))return response(429,{error:'Groq is rate-limited right now. Your action has not been applied.',retryAfter:1});if(!state)return response(400,{error:'missing state'});const next=structuredClone(state),action=body.action||'';next.turn++;let narrative='The Hollow Marches answer your action.';if(/healing potions/i.test(action)){next.potions--;next.hp=Math.min(next.maxHp,next.hp+7);narrative='The potion restores your strength.'}else if(/Second Wind/i.test(action)){next.secondWindReady=false;next.hp=Math.min(next.maxHp,next.hp+8);narrative='You find another reserve of strength.'}else{next.hp=Math.min(next.hp,10);next.lastRoll={dice:[15],die:15,modifier:1,total:16,dc:12,ability:'WIS',advantage:'normal',success:true,critical:false}}next.narrative=narrative;next.time='Dusk, moments later';next.history=[...next.history,{action,narrative}].slice(-6);next.suggestions=['Continue','Look around','Speak'];state=next;return response(200,{state,save:'dom-save-'+(++seq)+'-abcdefghijk',resolution:{kind:'none'}})};
  w.eval(read('engine.js'));w.eval(read('world.js'));await wait(0);return {dom,w,getState:()=>state};
}
(async()=>{
  let app=await openWorld();let {dom,w}=app;const d=w.document;await until(()=>/ready/i.test(d.querySelector('#availability').textContent),'DM readiness did not render');d.querySelector('#name').value='DOM Tester';d.querySelector('input[value="fighter"]').checked=true;d.querySelector('#heroform').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>!d.querySelector('#game').hidden,'character creation did not finish');assert.equal(d.querySelector('#heroName').textContent,'DOM Tester');assert.equal(d.querySelector('#potion').disabled,true);assert.equal(d.querySelector('#wind').hidden,false);assert.equal(d.querySelector('#wind').disabled,true);
  d.querySelector('#input').value='I examine the woman';d.querySelector('#command').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('#chapterNo').textContent==='TURN 1','turn did not finish');assert.match(d.querySelector('#story').textContent,/Rain beads on your cloak/,'prologue vanished after a turn');assert.match(d.querySelector('#story').textContent,/I examine the woman/);assert.equal(d.querySelector('#potion').disabled,false);assert.equal(d.querySelector('#wind').disabled,false);
  d.querySelector('#wind').click();await until(()=>d.querySelector('#chapterNo').textContent==='TURN 2','Second Wind turn did not finish');assert.match(d.querySelector('#pack').textContent,/Second Wind spent/);assert.equal(d.querySelector('#wind').disabled,true);const persisted=JSON.parse(w.localStorage.getItem('astra-open-world-v3'));assert.equal(persisted.state.name,'DOM Tester');dom.window.close();

  app=await openWorld(JSON.stringify({state:{version:3,cls:'fighter'},save:'broken-save'}));({dom,w}=app);await wait(0);assert.equal(w.document.querySelector('#creation').hidden,false,'corrupt save should be discarded');assert.equal(w.localStorage.getItem('astra-open-world-v3'),null);dom.window.close();

  const classic=new JSDOM(read('classic.html'),{url:'http://game.test/classic.html',runScripts:'outside-only',pretendToBeVisual:true});w=classic.window;browserStubs(w);w.Math.random=()=>.99;w.eval(read('engine.js'));w.eval(read('app.js'));const cd=w.document;cd.querySelector('#name').value='Classic DOM';cd.querySelector('#heroform').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));const choose=pattern=>{const b=[...cd.querySelectorAll('#choices button')].find(x=>pattern.test(x.textContent));assert(b,'missing choice '+pattern);b.click()};choose(/Promise to find her daughter/);choose(/Read the opened graves/);choose(/Show Edrin’s token/);choose(/Lead the girl back to the gate/);choose(/Save the ledger/);choose(/Leap across the broken balustrade/);choose(/Approach the bellkeeper/);choose(/Speak the name from the ledger/);assert.equal(cd.querySelector('#chapter').textContent,'THE KINDNESS OF A NAME');assert.match(cd.querySelector('#story').textContent,/ADVENTURE COMPLETE/);classic.window.close();
  console.log('DOM playtest passed: open-world creation/resources/turns/persistence/corrupt-save recovery and full classic peaceful route.');
})().catch(error=>{console.error(error);process.exit(1)});
